test_name: Check that addition works for multiple input / output combinations

# Write a data driven test for the addition API running at http://localhost:5000/add
# Parameterize the first_number and second_number fields in the request body, POST it
# to the endpoint and check that the element 'result' is present using the special !anything
# (bonus points if you *do* figure out how to actually check on the result value in a data
# driven manner :)

marks:
  - parametrize:
      key:
        - first_number
        - second_number
      vals:
        - [1, 1]
        - [0, 0]
        - [123, 123]
        - [999, 999]

stages:
  - name: Verify that adding two numbers works
    request:
      url: http://localhost:5000/add
      json:
        first_number: "{first_number}"
        second_number: "{second_number}"
      method: POST
    response:
      status_code: 200
      body:
        result: !anything