test_name: Check that getting US zip code 90210 results in HTTP status 200

stages:
  - name: Verify HTTP status code
    request:
      url: http://api.zippopotam.us/us/90210
      method: GET
    response:
      status_code: 200

---
test_name: Check that the response is in JSON

stages:
  - name: Verify Content-Type header value in response
    request:
      url: http://api.zippopotam.us/us/90210
      method: GET
    response:
      headers:
        content-type: application/json

---
test_name: Check that US zip code 90210 corresponds to Beverly Hills

stages:
  - name: Verify place name in response body
    request:
      url: http://api.zippopotam.us/us/90210
      method: GET
    response:
      body:
        places:
          - place name: Beverly Hills

---
test_name: Check place name for multiple combinations of country code and zip code

marks:
  - parametrize:
      key:
        - country_code
        - zip_code
        - place_name
      vals:
        - [us, 12345, Schenectady]
        - [ca, B2A, North Sydney South Central]
        - [nl, 3825, Vathorst]

stages:
  - name: Verify place name in response body
    request:
      url: http://api.zippopotam.us/{country_code}/{zip_code}
      method: GET
    response:
      body:
        places:
          - place name: "{place_name}"
