test_name: Check that US zip code 90210 corresponds to Beverly Hills

stages:
  - name: Verify place name in response body
    request:
      url: http://api.zippopotam.us/us/90210
      method: GET
    response:
      body:
        places:
          - place name: Beverly Hills

---
test_name: Check that getting US zip code 90210 results in HTTP status 200

stages:
  - name: Verify HTTP status code
    request:
      url: http://api.zippopotam.us/us/90210
      method: GET
    response:
      status_code: 200