test_name: Check that server is alive

stages:
  - name: Verify test endpoint returns expected success message
    request:
      url: http://localhost:5000/test
      method: GET
    response:
      status_code: 200
      body:
        message: success

---
test_name: Make sure server doubles number properly

stages:
  - name: Make sure number is returned correctly
    request:
      url: http://localhost:5000/add
      json:
        first_number: 5
        second_number: 6
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        result: 11